image:
  name: klakegg/hugo:edge-ext-alpine
  entrypoint: [""] #https://github.com/klakegg/docker-hugo/issues/13

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  #HUGO_VERSION: "0.75.1"
  HUGO_ENABLEGITINFO: "true"
  HUGO_ENV: "production"
  BASE_URL: "https://davidaparicio.gitlab.io/website"

pages:
  script:
  - hugo --cleanDestinationDir --minify --baseURL $BASE_URL
  artifacts:
    paths:
    - public
  only:
  - master

# - hugo --cleanDestinationDir --minify --debug --baseURL $BASE_URL
# test:
#   script:
#   - hugo
#   except:
#   - master

# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# https://discourse.gohugo.io/t/hugo-starter-error/28550/2
#image: registry.gitlab.com/pages/hugo:latest
#image: registry.gitlab.com/pages/hugo/hugo_extended:latest