# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: klakegg/hugo:0.75.1-ext-alpine
# https://discourse.gohugo.io/t/hugo-starter-error/28550/2
#image: registry.gitlab.com/pages/hugo:latest
#image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  #HUGO_VERSION: "0.75.1"
  HUGO_ENABLEGITINFO: "true"
  HUGO_ENV: "production"

# test:
#   script:
#   - hugo
#   except:
#   - master

pages:
  script:
  - hugo --cleanDestinationDir --minify --debug #--gc --minify #-b $URL
  artifacts:
    paths:
    - public
  only:
  - master
