---
# WARN[0000] ./docker-compose.yml: `version` is obsolete
#version: "3.8" #https://docs.docker.com/compose/compose-file/

services:
  simple:
    image: "traefik/whoami"
    container_name: "whoami"
    ports:
      - "1414:8080"
    command:
      - "--name=iamfoo"
      - "--port=8080"
  hugo-academic:
    # https://hub.docker.com/r/klakegg/hugo/tags?page=1&name=edge-ext-alpine
    image: "klakegg/hugo:edge-ext-alpine" #"klakegg/hugo:0.95.0-ext-alpine"
    container_name: "hugo"
    restart: "no"
    environment:
      - HUGO_ENV=production
    volumes:
      - .:/src
    ports: [ "1313:1313", ]
    # https://forum.gitlab.com/t/error-command-error-unknown-command-sh-for-hugo/95376
    entrypoint: [""] # FIX for Error: unknown command "hugo --help" for "hugo"
    command: hugo server --disableFastRender --bind 0.0.0.0 --printI18nWarnings