version: "3"

services:
  hugo:
    image: klakegg/hugo:0.88.0-ext-alpine
    container_name: "hugo-academic"
    restart: "no"
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#restart
    #"no", always, on-failure, unless-stopped
    environment:
      - HUGO_ENV=production
      #- HUGO_REFRESH_TIME=60
      #- GIT_SUBMODULE_STRATEGY=recursive
      #- HUGO_THEME=academic
      #- HUGO_WATCH=1
      #- HUGO_ENABLEGITINFO="true"
      #- HUGO_DESTINATION=/output
      #- HUGO_BASEURL=<your-url-here>
    volumes:
      - .:/src
    ports: [ "1313:1313", ]
    command:
    - server --disableFastRender --i18n-warnings

# https://net-security.fr/system/deploiement-automatique-dhugo-avec-gitlab-docker/
# https://gitlab.com/tzkuat/hugo-site/-/tree/master

# https://discourse.gohugo.io/t/docker-official-repo-for-hugo/144
# https://discourse.gohugo.io/t/klakeggs-wonderful-hugo-docker-image-update-thread/20347/3
# https://hub.docker.com/r/klakegg/hugo/
# https://hub.docker.com/r/jojomi/hugo/
# https://discourse.gohugo.io/t/binding-server-to-local-ip-or-0-0-0-0-does-not-work/18999/11